# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Clone only the main branch
    git clone --single-branch --branch main https://lryyihpu3jnjjjtlcpe3tbzxwny377dwf6qzgrcmbovahxjqfblq@dev.azure.com/btelligent/GCP%20ML%20Demos/_git/GCP%20ML%20Demos GCP%20ML%20Demos
    cd GCP%20ML%20Demos

    # Set up GitHub remote
    git remote add github https://btgrbo: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@github.com/btgrbo/GCP_ML_Demos.git

    # Push the main branch to GitHub
    git push github main
  displayName: 'Mirror main branch to GitHub'