options:
  logging: "CLOUD_LOGGING_ONLY"

steps:

  # Build the Docker images for demo 1
  - id: 'Step1'
    name: 'gcr.io/cloud-builders/docker'
    script: | 
      REGISTRY=europe-west3-docker.pkg.dev/bt-int-ml-specialization/ml-demo1

      docker build -t $REGISTRY/train:latest .
    dir: ./python/demo1/training
    waitFor: ['-']

  - id: 'Step2'
    name: 'gcr.io/cloud-builders/docker'
    script: | 
      REGISTRY=europe-west3-docker.pkg.dev/bt-int-ml-specialization/ml-demo1

      docker build -t $REGISTRY/dataflow_batch:latest     -f Dockerfile.batch     .
      docker build -t $REGISTRY/dataflow_eval:latest      -f Dockerfile.eval      .
      docker build -t $REGISTRY/dataflow_inference:latest -f Dockerfile.inference .
    dir: ./python/demo1/dataflow
    waitFor: ['-']

  # Push the Docker images to Artifact Registry for demo 1
  - id: 'Step3'
    name: 'gcr.io/cloud-builders/docker'
    script: |
      REGISTRY=europe-west3-docker.pkg.dev/bt-int-ml-specialization/ml-demo1

      docker push $REGISTRY/train:latest
      docker push $REGISTRY/dataflow_batch:latest
      docker push $REGISTRY/dataflow_eval:latest
      docker push $REGISTRY/dataflow_inference:latest
    waitFor: ['Step1', 'Step2']


  # Build the Docker images for demo 2
  - id: 'Step4'
    name: 'gcr.io/cloud-builders/docker'
    script: | 
      REGISTRY=europe-west3-docker.pkg.dev/bt-int-ml-specialization/ml-demo2

      docker build -t $REGISTRY/train:latest      -f Dockerfile.training   .
      docker build -t $REGISTRY/prediction:latest -f Dockerfile.prediction .

    dir: ./python/demo2
    waitFor: ['-']

  # Push the Docker images to Artifact Registry for demo 2
  - id: 'Step5'
    name: 'gcr.io/cloud-builders/docker'
    script: |
      REGISTRY=europe-west3-docker.pkg.dev/bt-int-ml-specialization/ml-demo2

      docker push $REGISTRY/train:latest
      docker push $REGISTRY/prediction:latest

    waitFor: ['Step3']



# # Images to be stored in Artifact Registry
# images:
#   - 'europe-west3-docker.pkg.dev/bt-int-ml-specialization/ml-demo1/train:latest'
