# europe-west3-docker.pkg.dev/bt-int-ml-specialization/ml-demo1/beam_python3.10_sdk:2.54.0rc1

# we need to use a pre-release runtime where https://github.com/apache/beam/issues/30062 is fixed

FROM python:3.10-slim

COPY --from=apache/beam_python3.8_sdk:2.40.0 /opt/apache/beam /opt/apache/beam

ENV BEAM_VERSION=2.54.0rc1

COPY requirements.txt .
RUN pip install --no-cache-dir -U -r ./requirements.txt

ENTRYPOINT [ "/opt/apache/beam/boot" ]